[build-system]
requires = ["hatchling>=1.11.0"]
build-backend = "hatchling.build"

[project]
name = "stubdefaulter"
version = "0.0.0"
description = "Autoadd default values to stubs"
requires-python = ">=3.10"
dependencies = ["libcst", "typeshed_client"]
